template quattor/client/version;

variable QUATTOR_RELEASE ?= '14.12.0-rc4';
variable QUATTOR_REPOSITORY_RELEASE ?= QUATTOR_RELEASE;
variable QUATTOR_PACKAGES_VERSION ?= QUATTOR_REPOSITORY_RELEASE + '_1';
