template quattor/client/version;

variable QUATTOR_RELEASE ?= '14.5.0-rc8';
variable QUATTOR_REPOSITORY_RELEASE ?= QUATTOR_RELEASE;
variable QUATTOR_PACKAGES_VERSION ?= QUATTOR_REPOSITORY_RELEASE + '_1';
