template quattor/client/version;

variable QUATTOR_RELEASE ?= '17.2.0-rc2';
variable QUATTOR_REPOSITORY_RELEASE ?= QUATTOR_RELEASE;
variable QUATTOR_PACKAGES_VERSION ?= QUATTOR_REPOSITORY_RELEASE + '_1';
